### PR TITLE
*.swp && fixes cabal install && template-haskell v2.9

### PR DESCRIPTION
**Pull request by rudymatela**
This pull request introduces 3 unrelated changes:
- `*.swp` on `.gitignore`.
- Fixes an error when installing with `cabal install`.
  - The `Stats` module was not exposed, that made any package using LSC crash with strange link errors.
- Fixes compilatios errors on template-haskell v2.9:
  - They introduced a change in `TySynInstD` constructors.
  - I could have used `if impl(template-haskell < v2.9) ... cpp-flags: LEGACYTH` to switch between the old and new APIs (I was lazy :grin: and don't have the older version to test here).  Also, I'm not sure if it's worth the cost of maintaining that.

Feel free to exclude any (or all) of the changes.

### CODE REVIEW

**Comment by jasonreich** [comment]
Interesting. It fails the Travis CI tests with an error I haven't seen before:
https://travis-ci.org/UoYCS-plasma/LazySmallCheck2012/builds/29268682

**Comment by rudymatela** [comment]
That's the actual error when cabal cannot satisfy dependencies:

```
...
rejecting: template-haskell-2.9.0.0 (conflict: base==4.6.0.1/installed-8aa...,
template-haskell => base==4.7.*)
rejecting: template-haskell-2.8.0.0, 2.7.0.0, 2.6.0.0, 2.5.0.0, 2.4.0.1,
2.4.0.0, 2.3.0.1, 2.3.0.0, 2.2.0.0 (conflict: lazysmallcheck2012 =>
template-haskell>=2.9 && <3)
Dependency tree exhaustively searched.
...
```

The error happens because, apparently, the default GHC for Travis is currently 7.6, and:
- Template Haskell versions <= **2.8** are for GHC **7.6**.
- Template Haskell **2.9** for GHC **7.8**.

So actually, using GHC 7.6, cabal is unable to satisfy the dependency.  I've added a line in `.travis.yml` indicating which GHC to use: `ghc: 7.8`.  The Travis build now passes!

This is probably a good indication that GHC 7.6 is still widely used and maybe maintaining both versions via CPP could be worth it.  Travis even has support of [compiling against two different versions of GHC at one go](http://docs.travis-ci.com/user/languages/haskell/).

**Comment by jasonreich** [comment]
Thanks for the contribution!

**Comment by rudymatela** [comment]
As a low-priority item in my TODO list is installing two different versions of GHC on my machine.  When I do that, I'll try to make a way for it to compile on both versions.

**Comment by rudymatela** [comment]
You're welcome!  Thanks for making LazySmallCheck2012 in the first place! :-D

**Pull request merged**
